version: 2
updates:
  # Configuration for Dockerfile
  

  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
